CREATE TABLE VEM_SER.ESTUDANTE (
	id NUMBER NOT NULL PRIMARY KEY, 
	nome VARCHAR2(200) NOT NULL, 
	data_nascimento DATE NOT NULL,
	nr_matricula NUMBER(10) UNIQUE NOT NULL,
	ativo CHAR
);

CREATE SEQUENCE VEM_SER.SEQ_ESTUDANTE 
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE; 

INSERT INTO VEM_SER.ESTUDANTE 
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Rafael', TO_DATE('03-03-2000', 'dd-mm-yyyy'), 1, 'S');

INSERT INTO VEM_SER.ESTUDANTE 
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Maicon', TO_DATE('20-02-1986', 'dd-mm-yyyy'), 2, 'S');

INSERT INTO VEM_SER.ESTUDANTE 
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Gustavo', TO_DATE('23-02-2003', 'dd-mm-yyyy'), 3, 'S');


INSERT INTO VEM_SER.ESTUDANTE 
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Felipe', TO_DATE('14-05-2007', 'dd-mm-yyyy'), 4, 'N');

INSERT INTO VEM_SER.ESTUDANTE 
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Matheus', TO_DATE('15-01-1984', 'dd-mm-yyyy'), 5, 'S');

INSERT INTO VEM_SER.ESTUDANTE 
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Ricardo', TO_DATE('30-01-2000', 'dd-mm-yyyy'), 6, 'N');

INSERT INTO VEM_SER.ESTUDANTE 
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Guilherme', TO_DATE('03-03-2004', 'dd-mm-yyyy'), 7, 'S');

INSERT INTO VEM_SER.ESTUDANTE 
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Luiz', TO_DATE('12-09-2002', 'dd-mm-yyyy'), 8, 'S');

INSERT INTO VEM_SER.ESTUDANTE 
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Pablo', TO_DATE('01-05-2003', 'dd-mm-yyyy'), 9, 'N');

INSERT INTO VEM_SER.ESTUDANTE 
(ID, NOME, DATA_NASCIMENTO, NR_MATRICULA , ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Henrique', TO_DATE('05-08-1999', 'dd-mm-yyyy'), 10, 'S');

SELECT * FROM ESTUDANTE;



